### PR TITLE
Switching docker compose to MySQL

### PR DESCRIPTION
**Pull request by StrajnarFilip**
This docker compose script uses MySQL instead of Postgres. It also has some aesthetic tweaks and better comments.

### CODE REVIEW

**Comment by robinshine** [comment]
Why switch to mysql? I think postgresql license is more open, and it also has more features.

**Comment by robinshine** [comment]
Also please submit pull request at OneDev itself for future contributions:
https://code.onedev.io/onedev/server/~pulls?query=open

**Comment by StrajnarFilip** [comment]
I'm glad you opened this discussion. I believe MySQL should have ever so slightly better performance. As for licensing, I thought MySQL (which uses GPLv2) uses more favourable license, but upon closer inspection, both appear to be [OSI approved](https://opensource.org/licenses/).
I suppose it would be a good idea to test the actual performance before making any such claims.

**Comment by StrajnarFilip** [comment]
> Also please submit pull request at OneDev itself for future contributions: https://code.onedev.io/onedev/server/~pulls?query=open

I will, sorry for the inconvenience.

**Comment by robinshine** [comment]
PostgreSQL uses similar license as BSD/MIT which is less restrictive. As to performance, I tested MySQL and PostgreSQL with OneDev previously and did not notice obvious difference. Both are more than enough for OneDev's usage scenario. 

OTOH PostgreSQL evolves much faster. In future versions, OneDev may only support PostgreSQL to utilize features such as built-in full text search, clustering, etc.

**Pull request closed without merging**
