### PR TITLE
Fix login-page in darkMode.

### PR DESCRIPTION
**Pull request by whwlsfb**
Fix login-page in darkMode background-img not cover.

### CODE REVIEW

**Comment by whwlsfb** [comment]
image

**Comment by whwlsfb** [comment]
image

**Comment by robinshine** [comment]
Thanks for the fix. What is your browser/version? I tested with Chrome/Firefox/Safari/Edge and they all work fine.

**Comment by whwlsfb** [comment]
Firefox: 97.0
Chrome: 98.0.4758.80

Screen resolution: 2560x1440 (I think this is the source of the problem)

Both has this problem

**Pull request merged**
